---
name: Require Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    paths-ignore:
      - .github/**

jobs:
  required-labels:
    runs-on:
      - self-hosted
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: approved
